webtalk_init -webtalk_dir D:/vivado_project/lab444/project_1/project_1.sim/sim_1/impl/timing/xsim/xsim.dir/counter_test_tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct  8 01:17:50 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8526f430-5275-4988-980b-d61d4ef5d1d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e559165286b74ea5aa188916df10ef7d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6776_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3782311583 -regid "" -xml D:/vivado_project/lab444/project_1/project_1.sim/sim_1/impl/timing/xsim/xsim.dir/counter_test_tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/vivado_project/lab444/project_1/project_1.sim/sim_1/impl/timing/xsim/xsim.dir/counter_test_tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/vivado_project/lab444/project_1/project_1.sim/sim_1/impl/timing/xsim/xsim.dir/counter_test_tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
